#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# https://typicode.github.io/husky/guide.html#with-env-variables
[ -n "$CI" ] && exit 0

yarn turbo run --concurrency=1 --filter=[HEAD^1] precommit
